# Generated by Django 4.2.5 on 2023-09-15 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('stock', models.PositiveIntegerField()),
                ('summary', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='book_image/')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('rental_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_book', to='books.book')),
                ('rental_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['return_date'],
            },
        ),
    ]
